version: "3.8"

services:
  n8n:
    build: .
    container_name: n8n-social-media
    ports:
      - "5678:3000"
    environment:
      - N8N_PORT=3000
      - NODE_ENV=production
      - WEBHOOK_URL=http://localhost:3000/
      - GENERIC_TIMEZONE=UTC
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=user
      - N8N_BASIC_AUTH_PASSWORD=pass
      # AWS Configuration
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_DEFAULT_REGION=${AWS_DEFAULT_REGION:-us-east-1}
      - AWS_DEFAULT_OUTPUT=${AWS_DEFAULT_OUTPUT:-json}
    volumes:
      - n8n_data:/home/node/.n8n
      - ./data:/data
    restart: unless-stopped

volumes:
  n8n_data:
